//created on: Oct 24, 2022
package rules

//list any import classes here.
import com.sbnz.chessanalyzer.model.piece.Piece;
import com.sbnz.chessanalyzer.model.piece.Knight;
import com.sbnz.chessanalyzer.model.piece.Bishop;
import com.sbnz.chessanalyzer.model.Square;
import com.sbnz.chessanalyzer.model.CanMoveOn;
import com.sbnz.chessanalyzer.model.Board;
//declare any global variables here








rule "LAST"
salience -100
  when
  	
    then
        System.out.println("Done");

end


