//created on: Oct 25, 2022
package rules

//list any import classes here.
import com.sbnz.chessanalyzer.model.piece.Piece;
import com.sbnz.chessanalyzer.model.piece.Knight;
import com.sbnz.chessanalyzer.model.Square;
import com.sbnz.chessanalyzer.model.CanMoveOn;
import com.sbnz.chessanalyzer.model.CanCapture;


//declare any global variables here

query findCanMoveOn( Piece piece, Square square )
  CanMoveOn(piece, square;)
end


query findCanCapture
  $cc : CanCapture($piece1, $piece2, $message;)
  $fromSquare : Square(piece == $piece1)
  $toSquare : Square(piece == $piece2)
end