//created on: Dec 10, 2022
package com.king

//list any import classes here.
import com.sbnz.chessanalyzer.model.piece.Piece;
import com.sbnz.chessanalyzer.model.piece.King;
import com.sbnz.chessanalyzer.model.Square;
import com.sbnz.chessanalyzer.model.CanMoveOn;
import com.sbnz.chessanalyzer.model.IsOnPath;
import com.sbnz.chessanalyzer.model.Board;
import com.sbnz.chessanalyzer.model.CanMoveOn.CanMoveOnType;
import com.sbnz.chessanalyzer.model.IsDefending;


//declare any global variables here



rule "King IsDefending Right Up Diagonal"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$k : King(this.equals($piece), $color : color)
		$s2 : Square(rank == $startRank + 1, file == $startFile + 1, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color == $color)    
	then
       insertLogical(new IsDefending($k,$p,$boardNumS));
end

rule "King IsDefending Right Down Diagonal"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$k : King(this.equals($piece), $color : color)
		$s2 : Square(rank == $startRank - 1, file == $startFile + 1, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color == $color)    
	then
       insertLogical(new IsDefending($k,$p,$boardNumS));
end

rule "King IsDefending Left Up Diagonal"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$k : King(this.equals($piece),$color : color)
		$s2 : Square(rank == $startRank + 1, file == $startFile - 1, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color == $color)    
	then
       insertLogical(new IsDefending($k,$p,$boardNumS));
end

rule "King IsDefending Left Down Diagonal"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$k : King(this.equals($piece),$color : color)
		$s2 : Square(rank == $startRank - 1, file == $startFile - 1, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color == $color)    
	then
       insertLogical(new IsDefending($k,$p,$boardNumS));
end

rule "King IsDefending Up"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$k : King(this.equals($piece), $color : color)
		$s2 : Square(rank == $startRank + 1, file == $startFile, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color == $color)    
	then
       insertLogical(new IsDefending($k,$p,$boardNumS));
end

rule "King IsDefending Down"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$k : King(this.equals($piece), $color : color)
		$s2 : Square(rank == $startRank - 1, file == $startFile, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color == $color)    
	then
       insertLogical(new IsDefending($k,$p,$boardNumS));
end

rule "King IsDefending Left"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$k : King(this.equals($piece), $color : color)
		$s2 : Square(rank == $startRank, file == $startFile - 1, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color == $color)    
	then
       insertLogical(new IsDefending($k,$p,$boardNumS));
end

rule "King IsDefending Right"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$k : King(this.equals($piece), $color : color)
		$s2 : Square(rank == $startRank, file == $startFile + 1, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color == $color)    
	then
       insertLogical(new IsDefending($k,$p,$boardNumS));
end
