//created on: Mar 16, 2023
package tactics

//list any import classes here.
import com.sbnz.chessanalyzer.model.IsAttacking;
import com.sbnz.chessanalyzer.model.IsDefending;
import com.sbnz.chessanalyzer.model.IsChecking;
import com.sbnz.chessanalyzer.model.piece.King;
import com.sbnz.chessanalyzer.model.piece.Piece;
import com.sbnz.chessanalyzer.model.CanCapture;
import java.util.List;
//declare any global variables here




rule "Is Checking"
    when
        $p : Piece()
        $k : King()
        IsAttacking($p, $k;)
    then
    	insertLogical(new IsChecking($p, $k));
        System.out.println("Piece " + $p.getFEN() + " Is Checking King");
end

rule "Is Attacking A Higher Value Piece"
    when
        $p1 : Piece($p1Value : value)
        $p2 : Piece(value > $p1Value)
        IsAttacking($p1, $p2;)
    then
        System.out.println("Piece " + $p1.getFEN() + " Is Attacking a Higher Value Piece and can capture" + $p2.getFEN());
        insertLogical(new CanCapture($p1, $p2));
end


rule "Is Attacking An Undefended piece"
    when
        IsAttacking($p1, $p2;)
        not IsDefending($p3, $p2;)
    then
        System.out.println("Piece " + $p1.getFEN() + " Can Capture Undefended Piece " + $p2.getFEN());
        insertLogical(new CanCapture($p1, $p2));
end


rule "Fork"
  when
  		$p : Piece($boardNum : boardNum)
  		$list : List(size >= 2) from collect(IsAttacking($p,$p2;))
    then
        System.out.println("Piece color: " + $p.getFEN() + " Is Forking " + $list.size()  + " pieces in");

end
