//created on: Nov 23, 2022
package com.queen

//list any import classes here.
import com.sbnz.chessanalyzer.model.piece.Piece;
import com.sbnz.chessanalyzer.model.piece.Queen;
import com.sbnz.chessanalyzer.model.Square;
import com.sbnz.chessanalyzer.model.CanMoveOn;
import com.sbnz.chessanalyzer.model.IsOnPath;
import com.sbnz.chessanalyzer.model.Board;
import com.sbnz.chessanalyzer.model.CanMoveOn.CanMoveOnType;
import com.sbnz.chessanalyzer.model.IsAttacking;


//declare any global variables here



rule "Queen First IsAttacking Right Up Diagonal"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$b : Queen(this.equals($piece), $color : color)
		$s2 : Square(rank == $startRank + 1, file == $startFile + 1, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color != $color)    
	then
       insertLogical(new IsAttacking($b,$p,$boardNumS));
end

rule "Queen IsAttacking Right Up Diagonal"
	when
		$s : Square($boardNumS : boardNum,  $startRank : rank, $startFile : file)
		$b : Queen($color : color)
		CanMoveOn($b,$s,CanMoveOnType.RIGHT_UP;)
		$s2 : Square(rank == $startRank + 1, file == $startFile + 1, boardNum == $boardNumS, $piece2 : piece)
		$p : Piece(this.equals($piece2), color != $color)
		
	then
		insertLogical(new IsAttacking($b,$p,$boardNumS));
end


rule "Queen First IsAttacking Right Down Diagonal"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$b : Queen(this.equals($piece), $color : color)
		$s2 : Square(rank == $startRank - 1, file == $startFile + 1, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color != $color)    
	then
       insertLogical(new IsAttacking($b,$p,$boardNumS));
end


rule "Queen IsAttacking Right Down Diagonal"
	when
		$s : Square($boardNumS : boardNum,  $startRank : rank, $startFile : file)
		$b : Queen($color : color)
		CanMoveOn($b,$s,CanMoveOnType.RIGHT_DOWN;)
		$s2 : Square(rank == $startRank - 1, file == $startFile + 1, boardNum == $boardNumS, $piece2 : piece)
		$p : Piece(this.equals($piece2), color != $color)
		
	then
		insertLogical(new IsAttacking($b,$p,$boardNumS));
end


rule "Queen First IsAttacking Left Up Diagonal"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$b : Queen(this.equals($piece),$color : color)
		$s2 : Square(rank == $startRank + 1, file == $startFile - 1, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color != $color)    
	then
       insertLogical(new IsAttacking($b,$p,$boardNumS));
end


rule "Queen IsAttacking Left Up Diagonal"
	when
		$s : Square($boardNumS : boardNum,  $startRank : rank, $startFile : file)
		$b : Queen($color : color)
		CanMoveOn($b,$s,CanMoveOnType.LEFT_UP;)
		$s2 : Square(rank == $startRank + 1, file == $startFile - 1, boardNum == $boardNumS, $piece2 : piece)
		$p : Piece(this.equals($piece2), color != $color)
		
	then
		insertLogical(new IsAttacking($b,$p,$boardNumS));
end

rule "Queen First IsAttacking Left Down Diagonal"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$b : Queen(this.equals($piece),$color : color)
		$s2 : Square(rank == $startRank - 1, file == $startFile - 1, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color != $color)    
	then
       insertLogical(new IsAttacking($b,$p,$boardNumS));
end


rule "Queen IsAttacking Left Down Diagonal"
	when
		$s : Square($boardNumS : boardNum,  $startRank : rank, $startFile : file)
		$b : Queen($color : color)
		CanMoveOn($b,$s,CanMoveOnType.LEFT_DOWN;)
		$s2 : Square(rank == $startRank - 1, file == $startFile - 1, boardNum == $boardNumS, $piece2 : piece)
		$p : Piece(this.equals($piece2), color != $color)
		
	then
		insertLogical(new IsAttacking($b,$p,$boardNumS));
end

rule "Queen First IsAttacking Up"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$r : Queen(this.equals($piece), $color : color)
		$s2 : Square(rank == $startRank + 1, file == $startFile, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color != $color)    
	then
       insertLogical(new IsAttacking($r,$p,$boardNumS));
end


rule "Queen IsAttacking Up"
	when
		$s : Square($boardNumS : boardNum,  $startRank : rank, $startFile : file)
		$r : Queen($color : color)
		CanMoveOn($r,$s,CanMoveOnType.UP;)
		$s2 : Square(rank == $startRank + 1, file == $startFile, boardNum == $boardNumS, $piece2 : piece)
		$p : Piece(this.equals($piece2), color != $color)
		
	then
		insertLogical(new IsAttacking($r,$p,$boardNumS));
end


rule "Queen First IsAttacking Down"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$r : Queen(this.equals($piece), $color : color)
		$s2 : Square(rank == $startRank - 1, file == $startFile, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color != $color)    
	then
       insertLogical(new IsAttacking($r,$p,$boardNumS));
end


rule "Queen IsAttacking Down"
	when
		$s : Square($boardNumS : boardNum,  $startRank : rank, $startFile : file)
		$r : Queen($color : color)
		CanMoveOn($r,$s,CanMoveOnType.DOWN;)
		$s2 : Square(rank == $startRank - 1, file == $startFile, boardNum == $boardNumS, $piece2 : piece)
		$p : Piece(this.equals($piece2), color != $color)
		
	then
		insertLogical(new IsAttacking($r,$p,$boardNumS));
end

rule "Queen First IsAttacking Left"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$r : Queen(this.equals($piece), $color : color)
		$s2 : Square(rank == $startRank, file == $startFile - 1, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color != $color)    
	then
       insertLogical(new IsAttacking($r,$p,$boardNumS));
end


rule "Queen IsAttacking Left"
	when
		$s : Square($boardNumS : boardNum,  $startRank : rank, $startFile : file)
		$r : Queen($color : color)
		CanMoveOn($r,$s,CanMoveOnType.LEFT;)
		$s2 : Square(rank == $startRank, file == $startFile - 1, boardNum == $boardNumS, $piece2 : piece)
		$p : Piece(this.equals($piece2), color != $color)
		
	then
		insertLogical(new IsAttacking($r,$p,$boardNumS));
end

rule "Queen First IsAttacking Right"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$r : Queen(this.equals($piece), $color : color)
		$s2 : Square(rank == $startRank, file == $startFile + 1, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color != $color)    
	then
       insertLogical(new IsAttacking($r,$p,$boardNumS));
end


rule "Queen IsAttacking Right"
	when
		$s : Square($boardNumS : boardNum,  $startRank : rank, $startFile : file)
		$r : Queen($color : color)
		CanMoveOn($r,$s,CanMoveOnType.RIGHT;)
		$s2 : Square(rank == $startRank, file == $startFile + 1, boardNum == $boardNumS, $piece2 : piece)
		$p : Piece(this.equals($piece2), color != $color)
		
	then
		insertLogical(new IsAttacking($r,$p,$boardNumS));
end

/*
rule "LAST2"
salience -99
  when
  		$r : Queen($boardNum : boardNum)
  		IsAttacking($r,$p;)
  		$s : Square(piece == $p, $squareText : squareText)
  		$b : Board(boardNum == $boardNum, $fen : fen)
    then
        System.out.println("Rook color: " + $r.getColor() + " Is Attacking on square: " + $squareText + " in position " + $fen);

end
*/