//created on: Nov 22, 2022
package rules.rook

//list any import classes here.
import com.sbnz.chessanalyzer.model.piece.Piece;
import com.sbnz.chessanalyzer.model.piece.Rook;
import com.sbnz.chessanalyzer.model.Square;
import com.sbnz.chessanalyzer.model.CanMoveOn;
import com.sbnz.chessanalyzer.model.IsOnPath;
import com.sbnz.chessanalyzer.model.Board;
import com.sbnz.chessanalyzer.model.CanMoveOn.CanMoveOnType;
import com.sbnz.chessanalyzer.model.IsDefending;


//declare any global variables here




rule "Rook First IsDefending Up"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$r : Rook(this.equals($piece), $color : color)
		$s2 : Square(rank == $startRank + 1, file == $startFile, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color == $color)    
	then
       insertLogical(new IsDefending($r,$p,$boardNumS));
end


rule "Rook IsDefending Up"
	when
		$s : Square($boardNumS : boardNum,  $startRank : rank, $startFile : file)
		$r : Rook($color : color)
		CanMoveOn($r,$s,CanMoveOnType.UP;)
		$s2 : Square(rank == $startRank + 1, file == $startFile, boardNum == $boardNumS, $piece2 : piece)
		$p : Piece(this.equals($piece2), color == $color)
		
	then
		insertLogical(new IsDefending($r,$p,$boardNumS));
end


rule "Rook First IsDefending Down"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$r : Rook(this.equals($piece), $color : color)
		$s2 : Square(rank == $startRank - 1, file == $startFile, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color == $color)    
	then
       insertLogical(new IsDefending($r,$p,$boardNumS));
end


rule "Rook IsDefending Down"
	when
		$s : Square($boardNumS : boardNum,  $startRank : rank, $startFile : file)
		$r : Rook($color : color)
		CanMoveOn($r,$s,CanMoveOnType.DOWN;)
		$s2 : Square(rank == $startRank - 1, file == $startFile, boardNum == $boardNumS, $piece2 : piece)
		$p : Piece(this.equals($piece2), color == $color)
		
	then
		insertLogical(new IsDefending($r,$p,$boardNumS));
end

rule "Rook First IsDefending Left"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$r : Rook(this.equals($piece), $color : color)
		$s2 : Square(rank == $startRank, file == $startFile - 1, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color == $color)    
	then
       insertLogical(new IsDefending($r,$p,$boardNumS));
end


rule "Rook IsDefending Left"
	when
		$s : Square($boardNumS : boardNum,  $startRank : rank, $startFile : file)
		$r : Rook($color : color)
		CanMoveOn($r,$s,CanMoveOnType.LEFT;)
		$s2 : Square(rank == $startRank, file == $startFile - 1, boardNum == $boardNumS, $piece2 : piece)
		$p : Piece(this.equals($piece2), color == $color)
		
	then
		insertLogical(new IsDefending($r,$p,$boardNumS));
end

rule "Rook First IsDefending Right"

    when
    	$s : Square($piece : piece, $squareText : squareText, $startRank : rank, $startFile : file, $boardNumS : boardNum) 
		$r : Rook(this.equals($piece), $color : color)
		$s2 : Square(rank == $startRank, file == $startFile + 1, boardNum == $boardNumS,$piece2 : piece)
		$p : Piece(this.equals($piece2), color == $color)    
	then
       insertLogical(new IsDefending($r,$p,$boardNumS));
end


rule "Rook IsDefending Right"
	when
		$s : Square($boardNumS : boardNum,  $startRank : rank, $startFile : file)
		$r : Rook($color : color)
		CanMoveOn($r,$s,CanMoveOnType.RIGHT;)
		$s2 : Square(rank == $startRank, file == $startFile + 1, boardNum == $boardNumS, $piece2 : piece)
		$p : Piece(this.equals($piece2), color == $color)
		
	then
		insertLogical(new IsDefending($r,$p,$boardNumS));
end
/*
rule "LAST2"
salience -99
  when
  		$r : Rook($boardNum : boardNum)
  		IsDefending($r,$p;)
  		$s : Square(piece == $p, $squareText : squareText)
  		$b : Board(boardNum == $boardNum, $fen : fen)
    then
        System.out.println("Rook color: " + $r.getColor() + " Is Attacking on square: " + $squareText + " in position " + $fen);

end
*/